googleAnalytics = "UA-44979762-7"
baseURL = "https://flipt.io/"
languageCode = "en-us"
title = "Flipt"
theme = "book"
enableEmoji = true
enableRobotsTXT = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  BookMenuBundle = '/menu'
  BookLogo = '/img/logo.svg'
  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/markphelps/flipt.io'

  # Enable 'Edit this page' links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath = 'edit/master/content'
  BookToC = 1
